# Generated by Django 3.1.3 on 2020-11-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.CharField(max_length=200)),
                ('answer_2', models.CharField(max_length=200)),
                ('answer_3', models.CharField(max_length=200)),
                ('answer_4', models.CharField(max_length=200)),
                ('answer_5', models.CharField(max_length=200)),
                ('game_id', models.BigIntegerField()),
                ('player_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.BigIntegerField()),
                ('evaluation_player_1', models.CharField(max_length=50)),
                ('evaluation_player_2', models.CharField(max_length=50)),
                ('evaluation_player_3', models.CharField(max_length=50)),
                ('evaluation_player_4', models.CharField(max_length=50)),
                ('evaluation_player_5', models.CharField(max_length=50)),
                ('player_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('game_id', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_players', models.BigIntegerField()),
                ('game_time_in_s', models.BigIntegerField()),
                ('game_letter', models.CharField(max_length=1)),
                ('game_id', models.BigIntegerField()),
                ('category_1', models.CharField(max_length=50)),
                ('category_2', models.CharField(max_length=50)),
                ('category_3', models.CharField(max_length=50)),
                ('category_4', models.CharField(max_length=50)),
                ('category_5', models.CharField(max_length=50)),
            ],
        ),
    ]
