# Generated by Django 3.1.2 on 2020-10-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.CharField(max_length=200)),
                ('answer_2', models.CharField(max_length=200)),
                ('answer_3', models.CharField(max_length=200)),
                ('answer_4', models.CharField(max_length=200)),
                ('answer_5', models.CharField(max_length=200)),
                ('game_id', models.BigIntegerField(max_length=6)),
                ('player_name', models.CharField(max_length=20)),
            ],
        ),
    ]
