# Generated by Django 3.1.2 on 2020-11-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation',
            name='evaluation_player_4',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluation_player_5',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
