# Generated by Django 3.1.2 on 2020-10-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_players', models.BigIntegerField(max_length=1)),
                ('game_time_in_s', models.BigIntegerField(max_length=3)),
                ('game_letter', models.CharField(max_length=1)),
                ('game_id', models.BigIntegerField(max_length=6)),
                ('category_1', models.CharField(max_length=50)),
                ('category_2', models.CharField(max_length=50)),
                ('category_3', models.CharField(max_length=50)),
                ('category_4', models.CharField(max_length=50)),
                ('category_5', models.CharField(max_length=50)),
            ],
        ),
    ]
