# Generated by Django 3.1.2 on 2020-11-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201109_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='game_time_in_s',
        ),
    ]
