# Generated by Django 3.1.2 on 2020-10-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation',
            name='e1_1',
            field=models.CharField(max_length=50),
        ),
    ]
